### ISSUE TITLE
getStatus and getHSB not working

### ISSUE THREAD

**Issue by bastardop** [matt-downs/homebridge-sonoff-tasmota-mqtt-hsb#1]
Hi,

ich have problems using this Homebridgeplugin with a Tasmota Sonoff flashed RGB Controller.

I can set On/Off and Color Values via MQTT and Homekit App without Problems und the Topics "cmnd/rgbled/Power" and "cmnd/rgbled/HSBColor"

but when tying to get the status via the get Topics I have several malfunctions.
Starting with "getOn" the Topic therefor is 

`stat/rgbled/POWER" and via Sonoff console and subscribing that channel is can see: "15:00:33 MQT: stat/rgbled/POWER = ON`

When sending this manually or via another control server Homebridge does not recognizing the stat change of the Rgbcontroler.
When setting the controller ON via Homebridge, it sets the led stripe to ON but in Home app it immediately changes the status back to OFF with leaving the Stripe on. Turn the strip off is know not possible via Home App.

The other Problem is the "getHSB" Topic, wenn setting it to "stat/rgbled/RESULT" I see this message in MQTT 

`15:07:26 MQT: stat/rgbled/RESULT = {"POWER":"ON","Dimmer":100,"Color":"0,255,41","HSBColor":"130,100,100","Channel":[0,100,16]}
`

and this Error I can see in Homebridge log:

`Nov 24 15:07:26 jarvis homebridge[16871]: Error: malformed HSBColor result:
Nov 24 15:07:26 jarvis homebridge[16871]: <Buffer 7b 22 50 4f 57 45 52 22 3a 22 4f 4e 22 2c 22 44 69 6d 6d 65 72 22 3a 31 30 30 2c 22 43 6f 6c 6f 72 22 3a 22 30 2c 32 35 35 2c 34 31 22 2c 22 48 53 42 ... >
`

Other MQTT Sonoff devices are working via Homebridge but everything using this Plugin can't use the get Topics.  Without Get Topics everything works fine in Homekit but when starting the Stripe via other controls Homekit can not really work with it

**Comment by bastardop** [comment]
ok first Problem could be solved by editing this line 
https://github.com/matt-downs/homebridge-sonoff-tasmota-mqtt-hsb/blob/9f7f330b65109e1663cfb598a403747b3ab7caa6/index.js#L93

from "On" to "ON"

**Comment by matt-downs** [comment]
@bastardop Thanks for the detailed info! what version of Sonoff-Tasmota are you running? I believe you can see this information if you go directly to your device in the browser. 

I'll definitely merge your changes for the first issue into the code, but I'm keen to work out what the second issue could be. I believe I may need to call `.toString()` on the `message` variable before I try and parse it to JSON on this line: 
https://github.com/matt-downs/homebridge-sonoff-tasmota-mqtt-hsb/blob/9f7f330b65109e1663cfb598a403747b3ab7caa6/index.js#L106

I'll run some tests this afternoon. 


@lukaszwitkowski are you using another homekit plugin to control your device from the browser? Let me know which one so I can test it out. 

Thanks! 😄

**Comment by lukaszwitkowski** [comment]
Hello matt 
I have updaten sonof-tasmota firmware to new i can control everything from my homekit app but if i use browser i dont see change in my homekit app. Everything else works great
I need that becouse i use „switch” in espboard to manual turn off and on and have status . But now it is not working

**Comment by lukaszwitkowski** [comment]
Matt ypu add something?

**Comment by bastardop** [comment]
@matt-downs I use Tasmota 6.3.0 with Arduino Core 2.3.0
I don't know if the default values for ON and OFF changed during Tasmota version. 
After I made the change to "ON" in the code I found the option to change the result values in Tasmota but I think to support the default values is the better way.

@lukaszwitkowski I think you have the same problems like me. with the changes in line 93 you could fix the problem with the ON / OFF state. 
but you also have to set the stat topic right, as they are case sensitiv

**Comment by bastardop** [comment]
@matt-downs I figured out what causes the .getHSB to throw the error
https://github.com/matt-downs/homebridge-sonoff-tasmota-mqtt-hsb/blob/9f7f330b65109e1663cfb598a403747b3ab7caa6/index.js#L108

when commenting out this line, everything works fine an the hsb value that is maybe set by another input than HomeKit is transfers right into HomeKit.

**Comment by matt-downs** [comment]
Hey guys, I’m going to push out a new version tonight after work - I’ll tag you when I do.

**Comment by matt-downs** [comment]
@bastardop @lukaszwitkowski 

I just pushed version 2.0.1 to npm which should fix the issues described in this thread. 🎉🎉🎉

You'll need to update your homebridge config file with the changes described here:
https://github.com/matt-downs/homebridge-sonoff-tasmota-mqtt-hsb#breaking-changes-in-200

Let me know if you continue to have issues even after updating

**Comment by lukaszwitkowski** [comment]
works great. everything ok . on/off status , dimmer and color too. grat job. now I need to use that in my Christmas tree.
