### ISSUE TITLE
Doesn't works

### ISSUE THREAD

**Issue by ptath** [matt-downs/homebridge-sonoff-tasmota-mqtt-hsb#5]
It can get status, but when I try to change colors or brightness via Home app in just try to turn it on/off

on/off:

```
22:46:29 MQT: stat/testrgb/RESULT = {"POWER":"ON"}
22:46:29 MQT: stat/testrgb/POWER = ON
```

change color:

`NOTHING`

change brightness:

```
22:49:10 MQT: stat/testrgb/RESULT = {"POWER":"ON"}
22:49:10 MQT: stat/testrgb/POWER = ON
```

If I try to do it via console (it works):

```
22:50:09 CMD: /cmnd/testrgb/color #00ff00
22:50:09 SRC: WebConsole from 192.168.1.196
22:50:09 RSL: Group 0, Index 1, Command COLOR, Data #00ff00
22:50:10 MQT: stat/testrgb/RESULT = {"POWER":"ON","Dimmer":100,"Color":"00FF00","HSBColor":"120,100,100","Channel":[0,100,0]}
22:50:10 CFG: Saved to flash at F6, Count 382, Bytes 3584
```

Dimmer, hsbcolor and so on works well via console.

Sonoff-tasmota 6.4.1, Nodemcu v.3 as MagicHome (34), RGB stripe, gpio R: 05, G: 14, B: 12.

**Comment by ptath** [comment]
My fault, mistype in config. What a shame )

**Comment by matt-downs** [comment]
@ptath glad you got it sorted 😄
